"use client";
import {useState,type FormEvent} from "react";
import {ArrowRight,CheckCircle2,Loader2,Building2,LockKeyhole} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Checkbox} from "@/components/ui/checkbox";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Alert,AlertDescription} from "@/components/ui/alert";
export function AgencyRegistrationForm({central=false,onCreated}:{central?:boolean;onCreated?:()=>void}){
 const [org,setOrg]=useState("องค์การบริหารส่วนตำบล");const [consent,setConsent]=useState(central);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[created,setCreated]=useState<{name:string;approvalStatus:string}|null>(null);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=new FormData(event.currentTarget);if(form.get('password')!==form.get('confirmation')){setError('รหัสผ่านทั้งสองช่องไม่ตรงกัน');return;}setBusy(true);
 try{const data={site:Object.fromEntries(['name','slug','province','district','phone','email'].map(k=>[k,String(form.get(k)||'').trim()])),username:form.get('username'),password:form.get('password'),contactName:form.get('contactName'),consent,website:form.get('website')||''};
 const res=await fetch(central?'/api/platform/agencies':'/api/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...data,site:{...data.site,organizationType:org}})});const body=await res.json();if(!res.ok)throw new Error(body.error||'ส่งคำขอไม่สำเร็จ');setCreated(body.site);onCreated?.();
 }catch(e){setError(e instanceof Error?e.message:'ส่งคำขอไม่สำเร็จ');}finally{setBusy(false);}}
 const field=(name:string,label:string,options:{type?:string;placeholder?:string;required?:boolean;pattern?:string;minLength?:number;maxLength?:number}={})=><div className="space-y-2"><Label htmlFor={`agency-${name}`}>{label}</Label><Input id={`agency-${name}`} name={name} type={options.type||'text'} required={options.required!==false} placeholder={options.placeholder} pattern={options.pattern} minLength={options.minLength} maxLength={options.maxLength||160} autoComplete={name==='password'||name==='confirmation'?'new-password':name==='username'?'username':undefined} className="h-11 text-base"/></div>;
 if(created)return <div className="space-y-5 py-6"><CheckCircle2 className="size-12 text-emerald-600"/><h2 className="text-2xl font-bold">{central?'เพิ่มหน่วยงานเรียบร้อย':'รับคำขอลงทะเบียนแล้ว'}</h2><p className="leading-7 text-slate-600">{created.name} — {central?'กรุณากลับไปรายการหน่วยงาน เพื่อกำหนดวันส่งงานและยืนยันเปิดใช้งาน':'กำลังรอผู้ดูแลระบบอนุมัติ เมื่ออนุมัติแล้ว เข้าระบบได้ด้วยชื่อผู้ใช้และรหัสผ่านที่คุณตั้งไว้'}</p><Button asChild><a href="/website">ไปหน้าเข้าสู่ระบบ <ArrowRight/></a></Button></div>;
 return <form onSubmit={submit} className="space-y-6">
  <div className="space-y-4"><h2 className="flex items-center gap-2 text-lg font-bold"><Building2 className="size-5 text-cyan-800"/>ข้อมูลหน่วยงาน</h2>{field('name','ชื่อหน่วยงาน',{placeholder:'องค์การบริหารส่วนตำบล…',minLength:3})}<div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="agency-type">ประเภทหน่วยงาน</Label><Select value={org} onValueChange={setOrg}><SelectTrigger id="agency-type" className="h-11 w-full"><SelectValue/></SelectTrigger><SelectContent>{['องค์การบริหารส่วนตำบล','เทศบาลตำบล','เทศบาลเมือง','เทศบาลนคร'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div>{field('slug','ชื่อเว็บไซต์ภาษาอังกฤษ',{placeholder:'เช่น banmai',pattern:'[a-z][a-z0-9]*(-[a-z0-9]+)*',minLength:3,maxLength:60})}{field('province','จังหวัด')}{field('district','อำเภอ')}{field('contactName','ชื่อผู้ประสานงาน')}{field('phone','โทรศัพท์ติดต่อ',{type:'tel',maxLength:50})}{field('email','อีเมลหน่วยงาน',{type:'email'})}</div></div>
  <div className="space-y-4 border-t pt-5"><h2 className="flex items-center gap-2 text-lg font-bold"><LockKeyhole className="size-5 text-cyan-800"/>บัญชีเข้าสู่ระบบ</h2>{field('username','Username',{placeholder:'เช่น banmai.staff',pattern:'[a-z][a-z0-9._-]{2,39}',maxLength:40})}<p className="text-sm text-slate-500">ภาษาอังกฤษตัวเล็ก 3–40 ตัว ใช้ตัวเลข จุด ขีดกลาง และขีดล่างได้</p><div className="grid gap-4 sm:grid-cols-2">{field('password','Password',{type:'password',minLength:12,maxLength:72,placeholder:'อย่างน้อย 12 ตัวอักษร'})}{field('confirmation','ยืนยัน Password',{type:'password',minLength:12,maxLength:72})}</div></div>
  <div hidden aria-hidden="true"><input name="website" tabIndex={-1} autoComplete="off"/></div>
  {!central&&<div className="flex items-start gap-3"><Checkbox id="agency-consent" checked={consent} onCheckedChange={v=>setConsent(v===true)} className="mt-1"/><Label htmlFor="agency-consent" className="text-sm leading-6">ยืนยันว่ามีสิทธิ์ประสานงานแทนหน่วยงาน และยินยอมให้ใช้ข้อมูลนี้เพื่อตรวจสอบคำขอและติดต่อกลับ</Label></div>}
  {error&&<Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}
  <Button type="submit" disabled={busy||!consent} className="h-12 w-full bg-[#0b5260] text-base">{busy?<Loader2 className="animate-spin"/>:<ArrowRight/>}{busy?'กำลังบันทึก…':central?'เพิ่มหน่วยงาน':'ส่งคำขอลงทะเบียน'}</Button>
 </form>;
}
