"use client";
import {useState,type FormEvent} from 'react';
import {Sparkles,Loader2,Copy,ExternalLink} from 'lucide-react';
import {Card,CardContent,CardHeader,CardTitle,CardDescription} from '@/components/ui/card';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
import {Label} from '@/components/ui/label';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Alert,AlertDescription} from '@/components/ui/alert';
import {toast} from 'sonner';
export type GeneratedMedia={id:string;fileName:string;url:string;contentType?:string;altText?:string};
export function AiImagePanel({siteId,isDemo,onCreated}:{siteId:string;isDemo?:boolean;onCreated:(file:GeneratedMedia)=>void}){
 const[prompt,setPrompt]=useState('');const[size,setSize]=useState('1536x1024');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[result,setResult]=useState<GeneratedMedia|null>(null);
 async function submit(e:FormEvent){e.preventDefault();if(isDemo){toast.info('เข้าสู่เว็บไซต์ของหน่วยงานเพื่อสร้างและบันทึกภาพ');return;}setBusy(true);setError('');try{const res=await fetch(`/api/sites/${siteId}/images`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),prompt,size})});const data=await res.json();if(!res.ok||!data.file)throw new Error(data.error||'สร้างภาพไม่สำเร็จ');setResult(data.file);onCreated(data.file);toast.success('สร้างภาพและบันทึกในคลังสื่อแล้ว');}catch(e){setError(e instanceof Error?e.message:'สร้างภาพไม่สำเร็จ');}finally{setBusy(false);}}
 return <Card className="border-cyan-200 bg-gradient-to-br from-cyan-50 to-white"><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="text-cyan-800"/>AI สร้างภาพ</CardTitle><CardDescription className="text-sm leading-6">พิมพ์สิ่งที่อยากเห็น เช่น กิจกรรมชุมชน สวนสาธารณะ หรือภาพประกอบการแยกขยะ ภาพที่สร้างจะเก็บในคลังสื่อของหน่วยงาน</CardDescription></CardHeader><CardContent className="space-y-5"><form onSubmit={submit} className="space-y-4"><div className="space-y-2"><Label htmlFor="ai-image-prompt">คำอธิบายภาพ</Label><Textarea id="ai-image-prompt" value={prompt} onChange={e=>setPrompt(e.target.value)} minLength={10} maxLength={2000} required disabled={busy} className="min-h-28 bg-white text-base" placeholder="ครอบครัวในชุมชนไทยช่วยกันแยกขยะที่สวนสาธารณะ บรรยากาศสดใส มีพื้นที่ว่างด้านซ้ายสำหรับวางข้อความ"/></div><div className="flex flex-col gap-3 sm:flex-row sm:items-end"><div className="flex-1 space-y-2"><Label htmlFor="ai-size">ขนาดภาพ</Label><Select value={size} onValueChange={setSize} disabled={busy}><SelectTrigger id="ai-size" className="h-11 w-full bg-white"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="1536x1024">แนวนอน — แบนเนอร์ / ข่าว</SelectItem><SelectItem value="1024x1024">จัตุรัส — ประชาสัมพันธ์</SelectItem><SelectItem value="1024x1536">แนวตั้ง — โปสเตอร์</SelectItem></SelectContent></Select></div><Button disabled={busy} className="h-11">{busy?<Loader2 className="animate-spin"/>:<Sparkles/>}{busy?'กำลังสร้างภาพ…':'สร้างภาพด้วย AI'}</Button></div><p className="text-sm text-slate-500">สร้างได้สูงสุด 20 ภาพต่อหน่วยงานใน 24 ชั่วโมง · ภาพจาก AI ใช้เป็นภาพประกอบ กรุณาตรวจทานก่อนเผยแพร่</p></form>{busy&&<p role="status" className="text-sm text-cyan-800">AI กำลังวาดภาพ กรุณารอสักครู่โดยเปิดหน้านี้ไว้</p>}{error&&<Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}{result&&<div className="overflow-hidden rounded-xl border bg-white"><img src={result.url} alt={result.altText||'ภาพที่สร้างจาก AI'} className="max-h-96 w-full object-contain"/><div className="flex flex-wrap gap-3 p-4"><Button variant="outline" type="button" onClick={async()=>{try{await navigator.clipboard.writeText(result.url);toast.success('คัดลอก URL แล้ว นำไปวางในช่องภาพได้');}catch{toast.error('คัดลอกไม่สำเร็จ เปิดภาพแล้วคัดลอกลิงก์ได้');}}}><Copy/>คัดลอกลิงก์ภาพ</Button><Button asChild variant="outline"><a href={result.url} target="_blank" rel="noreferrer"><ExternalLink/>เปิดภาพ</a></Button></div></div>}</CardContent></Card>;
}
