"use client";
import {useState,type FormEvent} from 'react';
import {Building2,Plus,Search,ExternalLink,CheckCircle2,Clock3,LogOut,Loader2,Settings2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Badge} from '@/components/ui/badge';
import {Card,CardContent} from '@/components/ui/card';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {AgencyRegistrationForm} from '@/components/agency-registration-form';
import type {AgencyRegistration} from '@/lib/platform';
import {toast} from 'sonner';
import {Toaster} from '@/components/ui/sonner';
const labels={pending:'รออนุมัติ',approved:'อนุมัติแล้ว',rejected:'ไม่อนุมัติ',suspended:'พักใช้งาน'};
export function PlatformConsole({initialAgencies,userName,startCreating=false}:{initialAgencies:AgencyRegistration[];userName:string;startCreating?:boolean}){
 const[agencies,setAgencies]=useState(initialAgencies);const[query,setQuery]=useState('');const[filter,setFilter]=useState('all');const[creating,setCreating]=useState(startCreating);const[editing,setEditing]=useState<AgencyRegistration|null>(null);const[busy,setBusy]=useState(false);
 async function refresh(){const res=await fetch('/api/platform/agencies');const data=await res.json();if(!res.ok)throw new Error(data.error);setAgencies(data.agencies);}
 async function review(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const form=new FormData(e.currentTarget);setBusy(true);try{const password=String(form.get('password')||'');const username=String(form.get('username')||'').trim();const status=String(form.get('action')||editing.approvalStatus);const res=await fetch(`/api/platform/agencies/${editing.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status,domainLabel:form.get('domainLabel'),...(username&&username!==editing.username?{username}:{}),...(password?{password}:{})})});const body=await res.json();if(!res.ok)throw new Error(body.error);await refresh();setEditing(null);toast.success('บันทึกหน่วยงานแล้ว');}catch(e){toast.error(e instanceof Error?e.message:'บันทึกไม่สำเร็จ');}finally{setBusy(false);}}
 async function logout(){await fetch('/api/auth/local/logout',{method:'POST'});window.location.assign('/admin/login');}
 const visible=agencies.filter(a=>(filter==='all'||a.approvalStatus===filter)&&`${a.name} ${a.slug} ${a.username} ${a.province}`.toLowerCase().includes(query.toLowerCase()));
 return <main className="min-h-svh bg-slate-50"><header className="bg-[#0b1f36] px-4 py-5 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4"><a href="/" className="flex items-center gap-3 text-xl font-bold"><Building2 className="size-7 text-amber-300"/> WebLocalGov <span className="hidden text-sm font-normal text-slate-300 sm:inline">หลังบ้านใหญ่</span></a><div className="flex items-center gap-3"><span className="text-sm text-slate-300">{userName}</span><Button variant="ghost" onClick={logout} aria-label="ออกจากระบบ"><LogOut/></Button></div></div></header>
 <div className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-cyan-800">ศูนย์บริหารหน่วยงาน</p><h1 className="mt-2 text-3xl font-bold">เว็บไซต์ของทุกชุมชน</h1><p className="mt-2 text-slate-600">ตรวจคำขอ อนุมัติบัญชี และตั้งที่อยู่เว็บไซต์</p></div><Button className="h-11" onClick={()=>setCreating(true)}><Plus/>เพิ่มหน่วยงาน</Button></div>
 <div className="grid gap-4 sm:grid-cols-3">{[{label:'หน่วยงานทั้งหมด',value:agencies.length,icon:Building2},{label:'รออนุมัติ',value:agencies.filter(a=>a.approvalStatus==='pending').length,icon:Clock3},{label:'เปิดใช้งานแล้ว',value:agencies.filter(a=>a.approvalStatus==='approved').length,icon:CheckCircle2}].map(x=><Card key={x.label}><CardContent className="flex items-center justify-between"><div><p className="text-sm text-slate-600">{x.label}</p><p className="mt-2 text-3xl font-bold">{x.value}</p></div><x.icon className="size-8 text-cyan-800"/></CardContent></Card>)}</div>
 <div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 size-5 text-slate-400"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาหน่วยงาน ชื่อเว็บไซต์ หรือชื่อผู้ใช้" className="h-11 bg-white pl-10"/></div><Select value={filter} onValueChange={setFilter}><SelectTrigger className="h-11 w-full bg-white sm:w-48"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">ทุกสถานะ</SelectItem>{Object.entries(labels).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div>
 <div className="space-y-3">{visible.map(a=><Card key={a.id} className="py-5"><CardContent className="flex flex-col gap-5 lg:flex-row lg:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><h2 className="text-lg font-bold">{a.name}</h2><Badge variant="outline" className={a.approvalStatus==='pending'?'bg-amber-50 text-amber-800':'bg-emerald-50 text-emerald-800'}>{labels[a.approvalStatus]}</Badge></div><p className="mt-2 text-sm text-slate-600">{a.contactName} · {a.province} · {a.phone||a.email}</p><p className="mt-2 break-all text-sm font-medium text-cyan-900">{a.domainLabel}.weblocalgov.com <span className="font-normal text-slate-500">· {a.domainStatus==='active'?'เชื่อมโดเมนแล้ว':'รอเชื่อมโดเมน'}</span></p><p className="mt-1 text-sm text-slate-500">Username: {a.username||'ยังไม่ได้ตั้ง'}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" asChild><a href={`/site/${a.slug}`} target="_blank" rel="noreferrer"><ExternalLink/>ดูเว็บ</a></Button><Button variant="outline" asChild><a href={`/admin/${a.id}`}>จัดการเนื้อหา</a></Button><Button onClick={()=>setEditing(a)}><Settings2/>{a.approvalStatus==='pending'?'ตรวจและอนุมัติ':'บัญชี / โดเมน'}</Button></div></CardContent></Card>)}{!visible.length&&<div className="rounded-2xl border border-dashed bg-white p-12 text-center text-slate-500">ยังไม่มีหน่วยงานในรายการนี้</div>}</div>
 </div>
 <Dialog open={creating} onOpenChange={setCreating}><DialogContent className="max-h-[92svh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>เพิ่มหน่วยงาน</DialogTitle><DialogDescription>ตั้งข้อมูลเว็บไซต์และบัญชีเจ้าหน้าที่ บัญชีที่เพิ่มจากส่วนกลางพร้อมใช้งานทันที</DialogDescription></DialogHeader><AgencyRegistrationForm key={String(creating)} central onCreated={()=>{void refresh();}}/></DialogContent></Dialog>
 <Dialog open={!!editing} onOpenChange={open=>!open&&!busy&&setEditing(null)}><DialogContent className="max-h-[92svh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>บัญชีและโดเมนหน่วยงาน</DialogTitle><DialogDescription>{editing?.name}</DialogDescription></DialogHeader>{editing&&<form key={editing.id} onSubmit={review} className="space-y-5"><div className="space-y-2"><Label htmlFor="domain-label">ชื่อโดเมน</Label><div className="flex items-center gap-2"><Input id="domain-label" name="domainLabel" defaultValue={editing.domainLabel} required pattern="[a-z][a-z0-9]*(-[a-z0-9]+)*" minLength={3} maxLength={60} className="min-w-0"/><span className="text-sm">.weblocalgov.com</span></div><p className="text-sm leading-6 text-slate-500">บันทึกชื่อก่อนเชื่อมโดเมน ระหว่างรอใช้ลิงก์ดูเว็บด้านบนได้</p></div><div className="space-y-2"><Label htmlFor="review-username">Username</Label><Input id="review-username" name="username" defaultValue={editing.username||''} placeholder="ตั้งชื่อผู้ใช้" autoComplete="off"/></div><div className="space-y-2"><Label htmlFor="review-password">ตั้งรหัสผ่านใหม่</Label><Input id="review-password" name="password" type="password" autoComplete="new-password" minLength={12} maxLength={72} placeholder="เว้นว่างเพื่อใช้รหัสเดิม"/></div><div className="space-y-2"><Label htmlFor="review-action">สถานะบัญชี</Label><Select name="action" defaultValue={editing.approvalStatus==='pending'?'approved':editing.approvalStatus}><SelectTrigger id="review-action" className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="approved">อนุมัติ / เปิดใช้งาน</SelectItem><SelectItem value="rejected">ไม่อนุมัติ</SelectItem><SelectItem value="suspended">พักใช้งาน</SelectItem></SelectContent></Select></div><Button disabled={busy} className="h-11 w-full">{busy?<Loader2 className="animate-spin"/>:<CheckCircle2/>}บันทึกและยืนยัน</Button></form>}</DialogContent></Dialog><Toaster richColors/>
 </main>;
}
